ifeq ($(PLATFORM),LINUX)
	GEN_BACKENDS_SOURCEDIRS = linux unix libc
	GEN_BACKENDS_COMMON_LFLAGS = -ldl -lm -lpthread
endif
ifeq ($(PLATFORM),OSX)
	GEN_BACKENDS_SOURCEDIRS = osx unix libc
	GEN_BACKENDS_COMMON_LFLAGS = -lpthread
endif

GEN_BACKENDS_PRIMARY = $(word 1,$(GEN_BACKENDS_SOURCEDIRS))
GEN_BACKENDS_SECONDARY = $(word 2,$(GEN_BACKENDS_SOURCEDIRS))
GEN_BACKENDS_TERTIARY = $(word 3,$(GEN_BACKENDS_SOURCEDIRS))
GEN_BACKENDS_QUATERNARY = $(word 4,$(GEN_BACKENDS_SOURCEDIRS))

ifneq ($(GEN_BACKENDS_PRIMARY),)
	GEN_BACKENDS_CFLAGS += -DGEN_BACKENDS_PRIMARY=\"$(GEN_BACKENDS_PRIMARY)\" 
endif
ifneq ($(GEN_BACKENDS_SECONDARY),)
	GEN_BACKENDS_CFLAGS += -DGEN_BACKENDS_SECONDARY=\"$(GEN_BACKENDS_SECONDARY)\"
endif
ifneq ($(GEN_BACKENDS_TERTIARY),)
	GEN_BACKENDS_CFLAGS += -DGEN_BACKENDS_TERTIARY=\"$(GEN_BACKENDS_TERTIARY)\"
endif
ifneq ($(GEN_BACKENDS_QUATERNARY),)
	GEN_BACKENDS_CFLAGS += -DGEN_BACKENDS_QUATERNARY=\"$(GEN_BACKENDS_QUATERNARY)\"
endif

GEN_BACKENDS_CFLAGS += $(GEN_BACKENDS_COMMON_CFLAGS) -I$(GENSTONE_DIR)/genstone/genbackends/include $(addsuffix /include,$(addprefix -I$(GENSTONE_DIR)/genstone/genbackends/,$(GEN_BACKENDS_SOURCEDIRS)))
GEN_BACKENDS_LIBDIRS += $(GENSTONE_DIR)/lib

GEN_BACKENDS_SOURCES = $(wildcard $(addsuffix /*.c,$(addprefix $(GENSTONE_DIR)/genstone/genbackends/,$(GEN_BACKENDS_SOURCEDIRS))))

GEN_BACKENDS_LIB = $(GENSTONE_DIR)/lib/$(LIB_PREFIX)genbackends$(STATIC_LIB_SUFFIX)

GEN_BACKENDS_LFLAGS += $(GEN_BACKENDS_COMMON_LFLAGS) $(BEGIN_FULL_STATIC)$(GEN_BACKENDS_LIB)$(END_FULL_STATIC)
