GEN_BACKENDS_INTERNAL_CFLAGS += $(GEN_BACKENDS_CFLAGS) $(GEN_CORE_CFLAGS) $(GENSTONE_DIAGNOSTIC_CFLAGS)
GEN_BACKENDS_INTERNAL_LFLAGS += $(GEN_BACKENDS_COMMON_LFLAGS)

GEN_BACKENDS_SANITIZERS = undefined,address

GEN_BACKENDS_OBJECTS = $(GEN_BACKENDS_SOURCES:.c=$(OBJECT_SUFFIX))

$(GEN_BACKENDS_LIB): CFLAGS = $(GEN_BACKENDS_INTERNAL_CFLAGS)
$(GEN_BACKENDS_LIB): LFLAGS = $(GEN_BACKENDS_INTERNAL_LFLAGS)
$(GEN_BACKENDS_LIB): LIBDIRS =
$(GEN_BACKENDS_LIB): SANITIZERS = $(GEN_BACKENDS_SANITIZERS)
$(GEN_BACKENDS_LIB): $(GEN_BACKENDS_OBJECTS) | $(GENSTONE_DIR)/lib

.PHONY: genbackends
genbackends: $(GEN_BACKENDS_LIB)

# It doesn't really make sense to test genbackends itself independent of gencore
.PHONY: test_genbackends
test_genbackends:

.PHONY: clean_genbackends
clean_genbackends:
	@$(ECHO) "$(ACTION_PREFIX)"
	-$(RM) $(GEN_BACKENDS_OBJECTS)
	-$(RM) $(GEN_BACKENDS_LIB)
	@$(ECHO) "$(ACTION_SUFFIX)"
