GEN_BACKENDS_CFLAGS = -I$(GENSTONE_DIR)/genstone/genbackends/include
GEN_BACKENDS_LFLAGS = $(GEN_BACKENDS_LIB)
GEN_BACKENDS_LIBDIRS = $(GENSTONE_DIR)/lib

PLATFORM_SOURCEDIRS := \
	$(addprefix $(GENSTONE_DIR)/genstone/genbackends/,$(PLATFORM_SOURCEDIRS))
PLATFORM_SOURCEDIRS := \
	$(addsuffix /*.c,$(PLATFORM_SOURCEDIRS))

GEN_BACKENDS_SOURCES = $(wildcard $(PLATFORM_SOURCEDIRS))

GEN_BACKENDS_LIB = \
	$(GENSTONE_DIR)/lib/$(LIB_PREFIX)genbackends$(STATIC_LIB_SUFFIX)

