include $(GENSTONE_DIR)/genstone/genbackends_selector.mk

GEN_CORE_COMMON_CFLAGS = -I$(GENSTONE_DIR)/genstone/gencore/include
GEN_CORE_COMMON_LFLAGS = $(GEN_BACKENDS_LFLAGS)

GEN_CORE_INTERNAL_CFLAGS = $(GENSTONE_DIAGNOSTIC_CFLAGS) $(GEN_BACKENDS_CFLAGS)
GEN_CORE_INTERNAL_CFLAGS += $(GEN_CORE_COMMON_CFLAGS)
GEN_CORE_INTERNAL_CFLAGS += -DGEN_BACKEND=\"$(PLATFORM)\"
GEN_CORE_INTERNAL_LFLAGS = $(GEN_CORE_COMMON_LFLAGS)

GEN_CORE_LIB = $(GENSTONE_DIR)/lib/$(LIB_PREFIX)gencore$(STATIC_LIB_SUFFIX)

GEN_CORE_CFLAGS = $(GEN_CORE_COMMON_CFLAGS)
GEN_CORE_LFLAGS = $(GEN_CORE_LIB) $(GEN_CORE_COMMON_LFLAGS)
GEN_CORE_LIBDIRS = $(GEN_BACKENDS_LIBDIRS) $(GENSTONE_DIR)/lib

GEN_CORE_SOURCES = $(wildcard $(GENSTONE_DIR)/genstone/gencore/*.c)
GEN_CORE_OBJECTS = $(GEN_CORE_SOURCES:.c=$(OBJECT_SUFFIX))

$(GEN_CORE_LIB): CFLAGS = $(GEN_CORE_INTERNAL_CFLAGS)
$(GEN_CORE_LIB): LFLAGS = $(GEN_CORE_INTERNAL_LFLAGS)
$(GEN_CORE_LIB): LIBDIRS = $(GEN_BACKENDS_LIBDIRS)
$(GEN_CORE_LIB): $(GEN_CORE_OBJECTS) $(GEN_BACKENDS_LIB) | $(GENSTONE_DIR)/lib

.PHONY: gencore
gencore: $(GEN_CORE_LIB)

.PHONY: test_gencore
test_gencore:

.PHONY: clean_gencore
clean_gencore:
	-$(RM) $(GEN_CORE_OBJECTS)
	-$(RM) $(GEN_CORE_LIB)
