SANDBOX_PROJECT_MODULE = sandbox/glean.mk
TOOLCHAIN = build/toolchain.mk
BUILD_MODE = DEBUG
TEST = DISABLED
PLATFORM = DEFAULT
IDE =
GLOBAL_C_FLAGS = -DGEN_USE_MIMALLOC=DISABLED
GLOBAL_L_FLAGS =
BORING_OUTPUT = DISABLED
AUTO_APPLY_FORMAT = ENABLED
TOOLING = DISABLED
STATIC_ANALYSIS = DISABLED
STRIP_BINARIES = DISABLED
ADDITIONAL_BUILD_MODULES =
DISABLED_MODULES =
BUILD_SYS_DEBUG = DISABLED
