Genstone: genstone/gencore/include/gemory.h File Reference
gemory.h File Reference
Macros
#define GEN_MEMORY_NO_BOUNDS SIZE_MAX
Functions
GEN_ERRORABLE gzalloc (void *restrict *const restrict out_address, const size_t count, const size_t size)
GEN_ERRORABLE gzalloc_aligned (void *restrict *const restrict out_address, const size_t count, const size_t size, const size_t align)
GEN_ERRORABLE grealloc (void *restrict *const restrict out_address, const size_t old_count, const size_t count, const size_t size)
GEN_ERRORABLE gfree (void *const restrict address)
GEN_ERRORABLE gen_memory_set (void *const restrict address, const size_t length, const unsigned char value)
GEN_ERRORABLE gen_memory_copy (const void *const restrict from, const size_t from_size, void *const restrict to, const size_t to_size, const size_t limit)
Detailed Description
Provides wrappers and abstraction for heap functions. Utility for managing memory.
Macro Definition Documentation
GEN_MEMORY_NO_BOUNDS
#define GEN_MEMORY_NO_BOUNDS SIZE_MAX
A value which can be used in place of buffer bounds in the event that no bounding should be performed.
Function Documentation
gen_memory_copy()
GEN_ERRORABLE gen_memory_copy (const void *const restrict from, const size_t from_size, void *const restrict to, const size_t to_size, const size_t limit)
Copies the data from one block of memory to another.
Parameters
[in] from the block from which to source the data.
[in] from_size the size of the source block in bytes.
[out] to the block to which to copy the data.
[in] to_size the size of the destination block in bytes.
[in] limit the number of bytes to copy.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_memory_copy);
     GEN_NULL_CHECK(from);
     GEN_NULL_CHECK(to);
     for(size_t i = 0; i < limit; ++i) {
         if(i >= from_size || i >= to_size) GEN_ERROR_OUT(GEN_OUT_OF_BOUNDS, "`i` ran outside of buffer bounds");
         ((uint8_t*) to)[i] = ((uint8_t*) from)[i];
     }
     GEN_ALL_OK;
 }
Referenced by gen_memory_copy().
gen_memory_set()
GEN_ERRORABLE gen_memory_set (void *const restrict address, const size_t length, const unsigned char value)
Sets a block of memory to a value.
Parameters
[out] address the buffer to set.
[in] length the length of the buffer to set in bytes.
[in] value the value to set the buffer to.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_memory_set);
     GEN_NULL_CHECK(address);
     for(unsigned char* d = address; d < (unsigned char*) address + length; ++d) {
         *d = value;
     }
     GEN_ALL_OK;
 }
Referenced by gen_memory_set().
gfree()
GEN_ERRORABLE gfree (void *const restrict address)
Frees a block of heap memory.
Parameters
[in] address the heap pointer to free.
Note
Contents of the block become undefined after freeing.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gfree);
     GEN_NULL_CHECK(address);
     GEN_MEMORY_FREE(address);
     GEN_ALL_OK;
 }
Referenced by gen_dylib_load(), gen_filewatch_poll(), gen_string_number(), gfree(), impl_thrd_routine(), and thrd_create().
grealloc()
GEN_ERRORABLE grealloc (void *restrict *const restrict out_address, const size_t old_count, const size_t count, const size_t size)
Resizes a memory block on the heap. May move items if new size is bigger than the old block allows.
Parameters
[in,out] out_address the heap pointer to resize. May be modified if block needs to be moved.
[in] old_count the previous number of units.
[in] count the number of units being allocated for.
[in] size the size of the unit being allocated for.
Returns
an error code.
{
     GEN_FRAME_BEGIN(grealloc);
     GEN_INTERNAL_GEMORY_PARAM_CHECK;
     void* const allocated = GEN_MEMORY_REALLOC(*out_address, count * size);
     GEN_ERROR_OUT_IF_ERRNO(GEN_MEMORY_REALLOC, errno);
     if(count > old_count) memset((unsigned char*) allocated + (size * old_count), 0, size * (count - old_count));
     *out_address = allocated;
     GEN_ALL_OK;
 }
Referenced by grealloc().
gzalloc()
GEN_ERRORABLE gzalloc (void *restrict *const restrict out_address, const size_t count, const size_t size)
Allocates memory on the heap. Ensures memory is zeroed before returning.
Parameters
[out] out_address pointer to storage for a pointer into the allocated heap block.
[in] count the number of units being allocated for.
[in] size the size of the unit being allocated for.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gzalloc);
     GEN_INTERNAL_GEMORY_PARAM_CHECK;
     void* const allocated = GEN_MEMORY_CALLOC(count, size);
     if(!allocated) GEN_ERROR_OUT_ERRNO(GEN_MEMORY_CALLOC, errno);
     *out_address = allocated;
     GEN_ALL_OK;
 }
Referenced by gen_dylib_load(), gen_string_duplicate(), gzalloc(), and thrd_create().
gzalloc_aligned()
GEN_ERRORABLE gzalloc_aligned (void *restrict *const restrict out_address, const size_t count, const size_t size, const size_t align)
Allocates memory on the heap. Ensures memory is zeroed before returning. Ensures memory is aligned to correct alignment.
Parameters
[out] out_address pointer to storage for a pointer into the allocated heap block.
[in] count the number of units being allocated for.
[in] size the size of the unit being allocated for.
[in] align the alignment to align allocation to.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gzalloc_aligned);
     GEN_INTERNAL_GEMORY_PARAM_CHECK;
     if(!align) GEN_ERROR_OUT(GEN_INVALID_PARAMETER, "`align` was 0");
     if(align & (align - 1)) GEN_ERROR_OUT(GEN_INVALID_PARAMETER, "`align` was not a power of 2");
     // Size must be a multiple of alignment
     const size_t aligned_size = (((count * size) / align) + 1) * align;
     void* const allocated = GEN_MEMORY_ALIGNED_ALLOC(align, aligned_size);
     if(!allocated) GEN_ERROR_OUT_ERRNO(GEN_MEMORY_ALIGNED_ALLOC, errno);
     *out_address = allocated;
     GEN_ALL_OK;
 }
Referenced by gen_filewatch_poll(), and gzalloc_aligned().