Genstone: genstone/gencore/include/genfs.h File Reference
genfs.h File Reference
#include "gencommon.h"
#include <unistd.h>
Data Structures
struct gen_filesystem_handle_t
Macros
#define GEN_PATH_MAX 1024
#define GEN_PATH_VALIDATION ENABLED
#define GEN_FS_FILEWATCH_USE_SYSLIB DISABLED
#define gen_stdin_handle ((gen_filesystem_handle_t){STDIN_FILENO, NULL, false, {0}, 0})
#define gen_stdout_handle ((gen_filesystem_handle_t){STDOUT_FILENO, NULL, false, {0}, 0})
#define gen_stderr_handle ((gen_filesystem_handle_t){STDERR_FILENO, NULL, false, {0}, 0})
Typedefs
typedef __nodiscard gen_error_t(* gen_directory_list_handler_t) (const char *const restrict, void *const restrict)
Enumerations
enum gen_filewatch_event_t {
GEN_FILEWATCH_NONE = 0, GEN_FILEWATCH_CREATED = 1, GEN_FILEWATCH_MODIFIED = 2, GEN_FILEWATCH_DELETED = 4,
GEN_FILEWATCH_MOVED = 8
}
Functions
GEN_ERRORABLE gen_path_canonical (char *restrict output_path, const char *const restrict path)
GEN_ERRORABLE gen_path_exists (const char *const restrict path, bool *const restrict out_exists)
GEN_ERRORABLE gen_path_validate (const char *const restrict path)
GEN_ERRORABLE gen_path_create_file (const char *const restrict path)
GEN_ERRORABLE gen_path_create_dir (const char *const restrict path)
GEN_ERRORABLE gen_path_delete (const char *const restrict path)
GEN_ERRORABLE gen_filesystem_handle_open (gen_filesystem_handle_t *restrict output_handle, const char *const restrict path)
GEN_ERRORABLE gen_filesystem_handle_close (gen_filesystem_handle_t *const restrict handle)
GEN_ERRORABLE gen_filesystem_handle_size (size_t *const restrict out_size, const gen_filesystem_handle_t *const restrict handle)
GEN_ERRORABLE gen_filesystem_handle_read (unsigned char *restrict output_buffer, const gen_filesystem_handle_t *const restrict handle, const size_t start, const size_t end)
GEN_ERRORABLE gen_filesystem_handle_write (const gen_filesystem_handle_t *const restrict handle, const size_t bytes_length, const unsigned char *const restrict buffer)
GEN_ERRORABLE gen_directory_list (const gen_filesystem_handle_t *const restrict handle, const gen_directory_list_handler_t handler, void *const restrict passthrough)
GEN_ERRORABLE gen_filewatch_create (gen_filesystem_handle_t *const restrict out_handle, const gen_filesystem_handle_t *const restrict handle)
GEN_ERRORABLE gen_filewatch_poll (gen_filesystem_handle_t *const restrict handle, gen_filewatch_event_t *const restrict out_event)
GEN_ERRORABLE gen_filewatch_destroy (gen_filesystem_handle_t *const restrict handle)
Detailed Description
Includes filesystem utilities for manipulation and introspection.
Macro Definition Documentation
GEN_FS_FILEWATCH_USE_SYSLIB
#define GEN_FS_FILEWATCH_USE_SYSLIB DISABLED
GEN_PATH_MAX
#define GEN_PATH_MAX 1024
The OS library's maximum length of a path.
GEN_PATH_VALIDATION
#define GEN_PATH_VALIDATION ENABLED
Whether to validate paths passed to genfs functions with gen_path_validate.
Note
Does not affect the presence of gen_path_validate.
gen_stderr_handle
#define gen_stderr_handle ((gen_filesystem_handle_t){STDERR_FILENO, NULL, false, {0}, 0})
gen_filesystem_handle_t wrapper for stderr.
gen_stdin_handle
#define gen_stdin_handle ((gen_filesystem_handle_t){STDIN_FILENO, NULL, false, {0}, 0})
gen_filesystem_handle_t wrapper for stdin.
gen_stdout_handle
#define gen_stdout_handle ((gen_filesystem_handle_t){STDOUT_FILENO, NULL, false, {0}, 0})
gen_filesystem_handle_t wrapper for stdout.
Typedef Documentation
gen_directory_list_handler_t
typedef __nodiscard gen_error_t(* gen_directory_list_handler_t) (const char *const restrict, void *const restrict)
Handler for directory listing.
Enumeration Type Documentation
gen_filewatch_event_t
enum gen_filewatch_event_t
Bitmasks for filewatch event reporting. Not all event types are reported on all platforms.
See also
gen_filewatch_poll
Enumerator
GEN_FILEWATCH_NONE
No event occurred.
GEN_FILEWATCH_CREATED
A file was created.
GEN_FILEWATCH_MODIFIED
A file was modified.
GEN_FILEWATCH_DELETED
A file was deleted.
GEN_FILEWATCH_MOVED
A file was moved.
 {
     /**
      * No event occurred.
      */
     GEN_FILEWATCH_NONE = 0,
     /**
      * A file was created.
      */
     GEN_FILEWATCH_CREATED = 1,
     /**
      * A file was modified.
      */
     GEN_FILEWATCH_MODIFIED = 2,
     /**
      * A file was deleted.
      */
     GEN_FILEWATCH_DELETED = 4,
     /**
      * A file was moved.
      */
     GEN_FILEWATCH_MOVED = 8
 } gen_filewatch_event_t;
Function Documentation
gen_directory_list()
GEN_ERRORABLE gen_directory_list (const gen_filesystem_handle_t *const restrict handle, const gen_directory_list_handler_t handler, void *const restrict passthrough)
Lists the contents of a directory.
Parameters
[in] handle a handle to a directory object to list from. Must not be a file.
[in] handler a handler to be called for each entry in the directory.
[in] passthrough a passthrough to the handler.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_directory_list);
     GEN_NULL_CHECK(handle);
     if(!handle->is_directory) GEN_ERROR_OUT(GEN_WRONG_OBJECT_TYPE, "`handle` was a file");
     GEN_NULL_CHECK(handler);
     rewinddir(handle->directory_handle);
     struct dirent* entry;
     while((entry = readdir(handle->directory_handle))) {
         GEN_ERROR_OUT_IF_ERRNO(readdir, errno);
         if(entry->d_name[0] == '.' && entry->d_name[1] == '\0') continue;
         if(entry->d_name[0] == '.' && entry->d_name[1] == '.' && entry->d_name[2] == '\0') continue;
         gen_error_t error = handler(entry->d_name, passthrough);
         GEN_ERROR_OUT_IF(error, "Call to directory list handler failed");
     }
     GEN_ERROR_OUT_IF_ERRNO(readdir, errno);
     rewinddir(handle->directory_handle);
     GEN_ALL_OK;
 }
Referenced by gen_directory_list(), gen_filewatch_create(), and gen_filewatch_poll().
gen_filesystem_handle_close()
GEN_ERRORABLE gen_filesystem_handle_close (gen_filesystem_handle_t *const restrict handle)
Closes a filesystem object handle. Storage of the handle may be reused after this call, though memory is not zeroed.
Parameters
[in] handle pointer to the handle to close.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_filesystem_handle_close);
     GEN_NULL_CHECK(handle);
     if(handle->is_directory) {
         closedir(handle->directory_handle);
         GEN_ERROR_OUT_IF_ERRNO(closedir, errno);
     }
     else {
         close(handle->file_handle);
         GEN_ERROR_OUT_IF_ERRNO(close, errno);
     }
     GEN_ALL_OK;
 }
Referenced by gen_filesystem_handle_close(), and gen_filewatch_destroy().
gen_filesystem_handle_open()
GEN_ERRORABLE gen_filesystem_handle_open (gen_filesystem_handle_t *restrict output_handle, const char *const restrict path)
Opens a path as a filesystem object handle for use by filesystem operations. Creates a file at path if nothing exists there already.
Parameters
[out] output_handle pointer to storage for the handle.
[in] path the path to open.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_filesystem_handle_open);
     GEN_NULL_CHECK(output_handle);
     GEN_INTERNAL_FS_PATH_PARAMETER_VALIDATION(path);
     int fd = open(path, O_DIRECTORY | O_RDONLY | O_CLOEXEC);
     if(errno == ENOTDIR) {
         errno = EOK;
         fd = open(path, O_RDWR | O_CLOEXEC);
         GEN_ERROR_OUT_IF_ERRNO(open, errno);
         output_handle->is_directory = false;
         output_handle->file_handle = fd;
         GEN_ALL_OK;
     }
     GEN_ERROR_OUT_IF_ERRNO(open, errno);
     output_handle->is_directory = true;
     output_handle->file_handle = fd;
     output_handle->directory_handle = fdopendir(fd);
     GEN_ERROR_OUT_IF_ERRNO(fdopendir, errno);
     GEN_ALL_OK;
 }
Referenced by gen_filesystem_handle_open().
gen_filesystem_handle_read()
GEN_ERRORABLE gen_filesystem_handle_read (unsigned char *restrict output_buffer, const gen_filesystem_handle_t *const restrict handle, const size_t start, const size_t end)
Gets a file's content.
Parameters
[out] output_buffer storage for the read bytes.
[in] handle a handle to a file object whose content to read. Must not be a directory.
[in] start an offset from the start of the file to begin reading from.
[in] end an offset from the start of the file to end reading from.
Note
Use gen_filesystem_handle_size as the end mark to read the whole file.
Does not add a null terminator to the buffer.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_filesystem_handle_read);
     GEN_NULL_CHECK(handle);
     if(handle->is_directory) GEN_ERROR_OUT(GEN_WRONG_OBJECT_TYPE, "`handle` was a directory");
     if(start >= end) GEN_ERROR_OUT(GEN_TOO_SHORT, "`start` >= `end`");
     GEN_NULL_CHECK(output_buffer);
     lseek(handle->file_handle, (long) start, SEEK_SET);
     GEN_ERROR_OUT_IF_ERRNO(lseek, errno);
     read(handle->file_handle, output_buffer, end - start);
     GEN_ERROR_OUT_IF_ERRNO(read, errno);
     lseek(handle->file_handle, 0, SEEK_SET);
     GEN_ERROR_OUT_IF_ERRNO(lseek, errno);
     GEN_ALL_OK;
 }
Referenced by gen_filesystem_handle_read().
gen_filesystem_handle_size()
GEN_ERRORABLE gen_filesystem_handle_size (size_t *const restrict out_size, const gen_filesystem_handle_t *const restrict handle)
Gets the size of a handle's object's content.
Parameters
[out] out_size a pointer to storage for the size of the handle.
[in] handle a handle to an object whose size to get. Must not be a directory.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_filesystem_handle_size);
     GEN_NULL_CHECK(handle);
     if(handle->is_directory) GEN_ERROR_OUT(GEN_WRONG_OBJECT_TYPE, "`handle` was a directory");
     size_t mark = (size_t) lseek(handle->file_handle, 0, SEEK_END);
     GEN_ERROR_OUT_IF_ERRNO(lseek, errno);
     lseek(handle->file_handle, 0, SEEK_SET);
     GEN_ERROR_OUT_IF_ERRNO(lseek, errno);
     *out_size = mark;
     GEN_ALL_OK;
 }
Referenced by gen_filesystem_handle_size().
gen_filesystem_handle_write()
GEN_ERRORABLE gen_filesystem_handle_write (const gen_filesystem_handle_t *const restrict handle, const size_t bytes_length, const unsigned char *const restrict buffer)
Writes to a file.
Parameters
[in] handle a handle to a file object to write to. Must not be a directory.
[in] bytes_length the number of bytes of buffer to write.
[in] buffer the buffer to source bytes from for writing.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_filesystem_handle_write);
     GEN_NULL_CHECK(handle);
     if(handle->is_directory) GEN_ERROR_OUT(GEN_WRONG_OBJECT_TYPE, "`handle` was a directory");
     GEN_NULL_CHECK(buffer);
     write(handle->file_handle, buffer, bytes_length);
     GEN_ERROR_OUT_IF_ERRNO(write, errno);
     lseek(handle->file_handle, 0, SEEK_SET);
     GEN_ERROR_OUT_IF_ERRNO(lseek, errno);
     GEN_ALL_OK;
 }
Referenced by gen_filesystem_handle_write().
gen_filewatch_create()
GEN_ERRORABLE gen_filewatch_create (gen_filesystem_handle_t *const restrict out_handle, const gen_filesystem_handle_t *const restrict handle)
Creates a filesystem watcher for a file or directory.
Parameters
[out] out_handle a pointer to storage for the created handle. This is not required to be the same as the filesystem handle used for IO.
[in] handle a filesystem handle to the file to watch.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_filewatch_create);
     GEN_NULL_CHECK(out_handle);
     GEN_NULL_CHECK(handle);
 #if PLATFORM == LNX && GEN_FS_FILEWATCH_USE_SYSLIB == ENABLED
     out_handle->is_directory = false;
     char pipe_name[GEN_PATH_MAX + 1] = {0};
     snprintf(pipe_name, GEN_PATH_MAX, "/proc/self/fd/%i", handle->file_handle);
     GEN_ERROR_OUT_IF_ERRNO(snprintf, errno);
     char path[GEN_PATH_MAX + 1] = {0};
     readlink(pipe_name, path, GEN_PATH_MAX);
     GEN_ERROR_OUT_IF_ERRNO(readlink, errno);
     out_handle->file_handle = inotify_init1(IN_NONBLOCK | IN_CLOEXEC);
     GEN_ERROR_OUT_IF_ERRNO(inotify_init1, errno);
     inotify_add_watch(out_handle->file_handle, path, IN_ATTRIB | IN_CREATE | IN_DELETE | IN_DELETE_SELF | IN_MODIFY | IN_MOVE_SELF | IN_MOVED_FROM | IN_MOVED_TO);
     GEN_ERROR_OUT_IF_ERRNO(inotify_add_watch, errno);
 #else
     out_handle->file_handle = dup(handle->file_handle);
     GEN_ERROR_OUT_IF_ERRNO(dup, errno);
     out_handle->is_directory = handle->is_directory;
     if(out_handle->is_directory) {
         out_handle->directory_handle = fdopendir(out_handle->file_handle);
         GEN_ERROR_OUT_IF_ERRNO(fdopendir, errno);
         gen_error_t error = gen_directory_list(handle, gen_internal_filewatch_dwn_dircount, &out_handle->internal_directory_length);
         GEN_ERROR_OUT_IF(error, "`gen_directory_list` failed");
     }
     fstat(out_handle->file_handle, &out_handle->internal_descriptor_details);
     GEN_ERROR_OUT_IF_ERRNO(fstat, errno);
 #endif
     GEN_ALL_OK;
 }
Referenced by gen_filewatch_create().
gen_filewatch_destroy()
GEN_ERRORABLE gen_filewatch_destroy (gen_filesystem_handle_t *const restrict handle)
Destroys a filesystem watcher.
Parameters
[in] handle the handle to the filesystem watcher to destroy. This is not required to be the same as the filesystem handle used for IO.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_filewatch_destroy);
     GEN_NULL_CHECK(handle);
 #if PLATFORM == LNX && GEN_FS_FILEWATCH_USE_SYSLIB == ENABLED
     close(handle->file_handle);
     GEN_ERROR_OUT_IF_ERRNO(close, errno);
 #else
     gen_error_t error = gen_filesystem_handle_close(handle);
     GEN_ERROR_OUT_IF(error, "`gen_filesystem_handle_close` failed");
 #endif
     GEN_ALL_OK;
 }
Referenced by gen_filewatch_destroy().
gen_filewatch_poll()
GEN_ERRORABLE gen_filewatch_poll (gen_filesystem_handle_t *const restrict handle, gen_filewatch_event_t *const restrict out_event)
Checks a filesystem watcher for events.
Parameters
[in] handle the handle to the filesystem watcher to check. This is not required to be the same as the filesystem handle used for IO.
[out] out_event pointer to storage for events which have occurred. Bitmask of gen_filewatch_event_t values.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_filewatch_poll);
     GEN_NULL_CHECK(handle);
     GEN_NULL_CHECK(out_event);
     *out_event = GEN_FILEWATCH_NONE;
 #if GEN_FS_FILEWATCH_USE_SYSLIB == ENABLED
     struct pollfd fd = {handle->file_handle, POLLIN, 0};
     fd.revents = 0;
     poll(&fd, 1, 0);
     GEN_ERROR_OUT_IF_ERRNO(poll, errno);
     if(fd.revents & POLLIN) {
         unsigned int events_size;
         ioctl(handle->file_handle, FIONREAD, &events_size);
         GEN_ERROR_OUT_IF_ERRNO(ioctl, errno);
         unsigned char* raw_events = NULL;
         gen_error_t error = gzalloc_aligned((void**) &raw_events, events_size, sizeof(unsigned char), alignof(struct inotify_event));
         GEN_ERROR_OUT_IF(error, "`gzalloc_aligned` failed");
         read(handle->file_handle, raw_events, events_size);
         if(errno != EOK) {
             error = gfree(raw_events);
             GEN_ERROR_OUT_IF(error, "`gfree` failed");
             GEN_ERROR_OUT_ERRNO(read, errno);
         }
         unsigned int offset = 0;
         while(offset < events_size) {
             struct inotify_event* const event = (struct inotify_event*) (raw_events + offset);
             if(event->mask & IN_ATTRIB || event->mask & IN_MODIFY) *out_event |= GEN_FILEWATCH_MODIFIED;
             if(event->mask & IN_CREATE) *out_event |= GEN_FILEWATCH_CREATED;
             if(event->mask & IN_DELETE || event->mask & IN_DELETE_SELF) *out_event |= GEN_FILEWATCH_DELETED;
             if(event->mask & IN_MOVE_SELF || event->mask & IN_MOVED_FROM || event->mask & IN_MOVED_TO) *out_event |= GEN_FILEWATCH_MOVED;
             offset += sizeof(struct inotify_event) + event->len;
         }
         error = gfree(raw_events);
         GEN_ERROR_OUT_IF(error, "`gfree` failed");
     }
     GEN_ALL_OK;
 #else
     struct stat file_info;
     fstat(handle->file_handle, &file_info);
     GEN_ERROR_OUT_IF_ERRNO(fstat, errno);
 #if PLATFORM == DWN
     if(!(file_info.st_mtimespec.tv_sec == handle->internal_descriptor_details.st_mtimespec.tv_sec && file_info.st_mtimespec.tv_nsec == handle->internal_descriptor_details.st_mtimespec.tv_nsec) || !(file_info.st_ctimespec.tv_sec == handle->internal_descriptor_details.st_ctimespec.tv_sec && file_info.st_ctimespec.tv_nsec == handle->internal_descriptor_details.st_ctimespec.tv_nsec)) {
 #else
     if(file_info.st_mtime != handle->internal_descriptor_details.st_mtime || file_info.st_ctime != handle->internal_descriptor_details.st_ctime) {
 #endif
         if(handle->is_directory) {
             size_t items_length = 0;
             gen_error_t error = gen_directory_list(handle, gen_internal_filewatch_dwn_dircount, &items_length);
             GEN_ERROR_OUT_IF(error, "`gen_directory_list` failed");
             if(handle->internal_directory_length > items_length)
                 *out_event |= GEN_FILEWATCH_DELETED;
             else if(handle->internal_directory_length < items_length)
                 *out_event |= GEN_FILEWATCH_CREATED;
             else
                 *out_event |= GEN_FILEWATCH_MODIFIED;
             handle->internal_directory_length = items_length;
         }
         else {
             *out_event |= GEN_FILEWATCH_MODIFIED;
         }
     }
     handle->internal_descriptor_details = file_info;
     GEN_ERROR_OUT_IF_ERRNO(memcpy_s, errno);
     GEN_ALL_OK;
 #endif
 }
Referenced by gen_filewatch_poll().
gen_path_canonical()
GEN_ERRORABLE gen_path_canonical (char *restrict output_path, const char *const restrict path)
Gets the canonical representation of a path.
Parameters
[out] output_path storage for the output path. Should be GEN_PATH_MAX + 1 in size if length is unknown.
[in] path the path to get a canonical representation for.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_path_canonical);
     GEN_NULL_CHECK(output_path);
     GEN_INTERNAL_FS_PATH_PARAMETER_VALIDATION(path);
     realpath(path, output_path);
     GEN_ERROR_OUT_IF_ERRNO(realpath, errno);
     GEN_ALL_OK;
 }
Referenced by gen_path_canonical().
gen_path_create_dir()
GEN_ERRORABLE gen_path_create_dir (const char *const restrict path)
Creates a directory.
Parameters
[in] path the directory path to create.
Returns
an error code.
Note
Will create with the default access flags for the platform, or a reasonable default if not applicable.
{
     GEN_FRAME_BEGIN(gen_path_create_dir);
     GEN_INTERNAL_FS_PATH_PARAMETER_VALIDATION(path);
     mkdir(path, 0777);
     GEN_ERROR_OUT_IF_ERRNO(mkdir, errno);
     GEN_ALL_OK;
 }
Referenced by gen_path_create_dir().
gen_path_create_file()
GEN_ERRORABLE gen_path_create_file (const char *const restrict path)
Creates a file.
Parameters
[in] path the file path to create.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_path_create_file);
     GEN_INTERNAL_FS_PATH_PARAMETER_VALIDATION(path);
     int descriptor = open(path, O_RDWR | O_CREAT | O_CLOEXEC, 0777);
     GEN_ERROR_OUT_IF_ERRNO(open, errno);
     close(descriptor);
     GEN_ERROR_OUT_IF_ERRNO(close, errno);
     GEN_ALL_OK;
 }
Referenced by gen_path_create_file().
gen_path_delete()
GEN_ERRORABLE gen_path_delete (const char *const restrict path)
Deletes a filesystem object.
Parameters
[in] path a path to the object to destroy.
Returns
an error code.
{
     GEN_FRAME_BEGIN(gen_path_delete);
     GEN_INTERNAL_FS_PATH_PARAMETER_VALIDATION(path);
     if(rmdir(path) == -1 && errno == ENOTDIR) {
         errno = EOK;
         unlink(path);
         GEN_ERROR_OUT_IF_ERRNO(unlink, errno);
         GEN_ALL_OK;
     }
     GEN_ERROR_OUT_IF_ERRNO(rmdir, errno);
     GEN_ALL_OK;
 }
Referenced by gen_path_delete().
gen_path_exists()
GEN_ERRORABLE gen_path_exists (const char *const restrict path, bool *const restrict out_exists)
Returns whether a filesystem object exists at a path.
Parameters
[in] path the path to check.
Returns
whether an object exists at path.
{
     GEN_FRAME_BEGIN(gen_path_exists);
     GEN_NULL_CHECK(out_exists);
     GEN_INTERNAL_FS_PATH_PARAMETER_VALIDATION(path);
     *out_exists = !access(path, F_OK);
     if(errno != ENOENT) GEN_ERROR_OUT_IF_ERRNO(access, errno);
     errno = EOK;
     GEN_ALL_OK;
 }
Referenced by gen_path_exists().
gen_path_validate()
GEN_ERRORABLE gen_path_validate (const char *const restrict path)
Checks whether a path is valid.
Parameters
[in] path the path to validate.
Returns
an error code. GEN_TOO_LONG or GEN_TOO_SHORT if a path is an invalid length. GEN_WRONG_OBJECT_TYPE if an invalid character is encountered in the path.
{
     GEN_FRAME_BEGIN(gen_path_validate);
     GEN_NULL_CHECK(path);
     if(!path[0]) GEN_ERROR_OUT(GEN_TOO_SHORT, "`path` was too short (`length(path)` was 0)");
     // This is a kinda nonsensical test but it feels like the best way to do this
     // Testing if length of path is less than GEN_PATH_MAX
     size_t path_length = 0;
     gen_error_t error = gen_string_length(path, GEN_PATH_MAX + 1, GEN_PATH_MAX, &path_length);
     GEN_ERROR_OUT_IF(error, "`gen_string_length` failed");
     GEN_ALL_OK;
 }
Referenced by gen_path_validate().