Genstone: genstone/gencore/threademu/threads.c File Reference
threads.c File Reference
#include "include/threads.h"
#include "../include/gencommon.h"
Functions
void * impl_thrd_routine (void *p)
void call_once (once_flag *flag, void(*func)(void))
int cnd_broadcast (cnd_t *cond)
void cnd_destroy (cnd_t *cond)
int cnd_init (cnd_t *cond)
int cnd_signal (cnd_t *cond)
int cnd_timedwait (cnd_t *cond, mtx_t *mtx, const struct timespec *abs_time)
int cnd_wait (cnd_t *cond, mtx_t *mtx)
void mtx_destroy (mtx_t *mtx)
int mtx_init (mtx_t *mtx, int type)
int mtx_lock (mtx_t *mtx)
int mtx_timedlock (mtx_t *mtx, const struct timespec *ts)
int mtx_trylock (mtx_t *mtx)
int mtx_unlock (mtx_t *mtx)
int thrd_create (thrd_t *thr, thrd_start_t func, void *arg)
thrd_t thrd_current (void)
int thrd_detach (thrd_t thr)
int thrd_equal (thrd_t thr0, thrd_t thr1)
noreturn void thrd_exit (int res)
int thrd_join (thrd_t thr, int *res)
void thrd_sleep (const struct timespec *time_point, struct timespec *remaining)
void thrd_yield (void)
int tss_create (tss_t *key, tss_dtor_t dtor)
void tss_delete (tss_t key)
void * tss_get (tss_t key)
int tss_set (tss_t key, void *val)
Function Documentation
call_once()
void call_once (once_flag * flag, void(*)(void) func)
{
     pthread_once(flag, func);
 }
cnd_broadcast()
int cnd_broadcast (cnd_t * cond)
{
     GEN_REQUIRE_NON_NULL(cond);
     return (pthread_cond_broadcast(cond) == 0) ? thrd_success : thrd_error;
 }
cnd_destroy()
void cnd_destroy (cnd_t * cond)
{
     GEN_REQUIRE_NON_NULL(cond);
     pthread_cond_destroy(cond);
 }
cnd_init()
int cnd_init (cnd_t * cond)
{
     GEN_REQUIRE_NON_NULL(cond);
     return (pthread_cond_init(cond, NULL) == 0) ? thrd_success : thrd_error;
 }
cnd_signal()
int cnd_signal (cnd_t * cond)
{
     GEN_REQUIRE_NON_NULL(cond);
     return (pthread_cond_signal(cond) == 0) ? thrd_success : thrd_error;
 }
cnd_timedwait()
int cnd_timedwait (cnd_t * cond, mtx_t * mtx, const struct timespec * abs_time)
{
     int rt;
     GEN_REQUIRE_NON_NULL(mtx);
     GEN_REQUIRE_NON_NULL(cond);
     GEN_REQUIRE_NON_NULL(abs_time);
     rt = pthread_cond_timedwait(cond, mtx, abs_time);
     if(rt == ETIMEDOUT)
         return thrd_busy;
     return (rt == 0) ? thrd_success : thrd_error;
 }
cnd_wait()
int cnd_wait (cnd_t * cond, mtx_t * mtx)
{
     GEN_REQUIRE_NON_NULL(mtx);
     GEN_REQUIRE_NON_NULL(cond);
     return (pthread_cond_wait(cond, mtx) == 0) ? thrd_success : thrd_error;
 }
impl_thrd_routine()
void* impl_thrd_routine (void * p)
{
     struct impl_thrd_param pack = *((struct impl_thrd_param*) p);
     gen_error_t error = gfree(p);
     GEN_REQUIRE_NO_ERROR(error);
     return (void*) (intptr_t) pack.func(pack.arg);
 }
Referenced by thrd_create().
mtx_destroy()
void mtx_destroy (mtx_t * mtx)
{
     GEN_REQUIRE_NON_NULL(mtx);
     pthread_mutex_destroy(mtx);
 }
mtx_init()
int mtx_init (mtx_t * mtx, int type)
{
     pthread_mutexattr_t attr;
     GEN_REQUIRE_NON_NULL(mtx);
     if(type != mtx_plain && type != mtx_timed && type != mtx_try && type != (mtx_plain | mtx_recursive) && type != (mtx_timed | mtx_recursive) && type != (mtx_try | mtx_recursive))
         return thrd_error;
     if((type & mtx_recursive) == 0) {
         pthread_mutex_init(mtx, NULL);
         return thrd_success;
     }
     pthread_mutexattr_init(&attr);
     pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
     pthread_mutex_init(mtx, &attr);
     pthread_mutexattr_destroy(&attr);
     return thrd_success;
 }
mtx_lock()
int mtx_lock (mtx_t * mtx)
{
     GEN_REQUIRE_NON_NULL(mtx);
     return (pthread_mutex_lock(mtx) == 0) ? thrd_success : thrd_error;
 }
mtx_timedlock()
int mtx_timedlock (mtx_t * mtx, const struct timespec * ts)
{
     GEN_REQUIRE_NON_NULL(mtx);
     GEN_REQUIRE_NON_NULL(ts);
     time_t expire = time(NULL);
     expire += ts->tv_sec;
     while(mtx_trylock(mtx) != thrd_success) {
         time_t now = time(NULL);
         if(expire < now)
             return thrd_busy;
         thrd_yield();
     }
     return thrd_success;
 }
mtx_trylock()
int mtx_trylock (mtx_t * mtx)
{
     GEN_REQUIRE_NON_NULL(mtx);
     return (pthread_mutex_trylock(mtx) == 0) ? thrd_success : thrd_busy;
 }
Referenced by mtx_timedlock().
mtx_unlock()
int mtx_unlock (mtx_t * mtx)
{
     GEN_REQUIRE_NON_NULL(mtx);
     return (pthread_mutex_unlock(mtx) == 0) ? thrd_success : thrd_error;
 }
thrd_create()
int thrd_create (thrd_t * thr, thrd_start_t func, void * arg)
{
     struct impl_thrd_param* pack;
     GEN_REQUIRE_NON_NULL(thr);
     gen_error_t error = gzalloc((void**) &pack, sizeof(struct impl_thrd_param), 1);
     GEN_REQUIRE_NO_ERROR(error);
     if(!pack) return thrd_nomem;
     pack->func = func;
     pack->arg = arg;
     if(pthread_create(thr, NULL, impl_thrd_routine, pack) != 0) {
         error = gfree(pack);
         GEN_REQUIRE_NO_ERROR(error);
         return thrd_error;
     }
     return thrd_success;
 }
thrd_current()
thrd_t thrd_current (void)
{
     return pthread_self();
 }
thrd_detach()
int thrd_detach (thrd_t thr)
{
     return (pthread_detach(thr) == 0) ? thrd_success : thrd_error;
 }
thrd_equal()
int thrd_equal (thrd_t thr0, thrd_t thr1)
{
     return pthread_equal(thr0, thr1);
 }
thrd_exit()
noreturn void thrd_exit (int res)
{
     pthread_exit((void*) (intptr_t) res);
 }
thrd_join()
int thrd_join (thrd_t thr, int * res)
{
     void* code;
     if(pthread_join(thr, &code) != 0)
         return thrd_error;
     if(res)
         *res = (int) (intptr_t) code;
     return thrd_success;
 }
thrd_sleep()
void thrd_sleep (const struct timespec * time_point, struct timespec * remaining)
{
     GEN_REQUIRE_NON_NULL(time_point);
     nanosleep(time_point, remaining);
 }
thrd_yield()
void thrd_yield (void)
                       {
     sched_yield();
 }
Referenced by mtx_timedlock().
tss_create()
int tss_create (tss_t * key, tss_dtor_t dtor)
{
     GEN_REQUIRE_NON_NULL(key);
     return (pthread_key_create(key, dtor) == 0) ? thrd_success : thrd_error;
 }
tss_delete()
void tss_delete (tss_t key)
{
     pthread_key_delete(key);
 }
tss_get()
void* tss_get (tss_t key)
{
     return pthread_getspecific(key);
 }
tss_set()
int tss_set (tss_t key, void * val)
{
     return (pthread_setspecific(key, val) == 0) ? thrd_success : thrd_error;
 }