name: Documentation

on:
  push:
    branches: [ trunk ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
          
    steps:
      - uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install doxygen

      - name: Build
        run: make docs          

      - name: Publish
        run: |
          cd docs
          git init
          git branch -m documentation
          git config --global user.email "prs.ttg+gh@pm.me" # We'll just pretend it's me for now
          git config --global user.name "Th3T3chn0G1t"
          git remote add origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/Th3T3chn0G1t/GenesisEngine
          git add *
          git commit -m "Documentation build from latest changes"
          git push -f -u origin documentation
