name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: CI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Fetch Submodules
        run: git submodule update --init

      - name: Install Clang
        if: ${{ runner.os != 'macOS' }}
        uses: egor-tensin/setup-clang@v1

# For GLFW
#      - name: Install Dependencies
#        if: ${{ runner.os == 'Linux' }}
#        run: sudo apt-get install xorg-dev

      - name: Build & Test
        run: make
