name: Prebuilt Binaries

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Prebuilt Binaries for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    permissions:
      contents: write
          
    steps:
      - uses: actions/checkout@v2


      - name: Fetch Submodules
        run: git submodule update --init
        
      - name: Install Clang
        if: ${{ runner.os != 'macOS' }}
        uses: egor-tensin/setup-clang@v1
        
      - name: Install Automake
        if: ${{ runner.os != 'windows' }}
        uses: lyricwulf/abc@v1
        with:
          linux: automake
          macos: automake
        
      - name: Build
        run: OVERRIDE_TEST=NONE make

      - name: Publish
        run: |
          cd lib
          mkdir ${{ matrix.os }}-$(git rev-parse --short "$GITHUB_SHA")
          mv * ${{ matrix.os }}-$(git rev-parse --short "$GITHUB_SHA")
          
          git init
          git branch -m prebuilts
          git config --global user.email "prs.ttg+gh@pm.me" # We'll just pretend it's me for now
          git config --global user.name "Th3T3chn0G1t"
          git remote add origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/Th3T3chn0G1t/GenesisEngine
          git pull -u origin
          git add *
          git commit -m "Binary build from latest changes"
          git push -f -u origin prebuilts
